### ISSUE TITLE
Firebase crash: RejectedExecutionException Compose

### ISSUE THREAD

**Issue by emi-net21** [DevCycleHQ/android-client-sdk#144]
Hello, we saw a couple of crashes on Firebase related with DevCycle code.

We suppose that the method that is crashing is: **dvcClient.variable(...)** bc its the only method we use

We are using:
- devCycle = 1.4.2
- compose = 1.2.1

`Fatal Exception: java.util.concurrent.RejectedExecutionException: Task androidx.activity.d@52492b rejected from java.util.concurrent.ThreadPoolExecutor@7967188[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:624)
       at com.devcycle.sdk.android.eventsource.EventSource.start(EventSource.java:52)
       at com.devcycle.sdk.android.api.DVCClient.initEventSource(DVCClient.java:66)
       at com.devcycle.sdk.android.api.DVCClient.access$initEventSource(DVCClient.java)
       at com.devcycle.sdk.android.api.DVCClient$onResumeApplication$1$1$1.invokeSuspend(:31)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:8)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:86)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:12)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:9)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:9)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:9)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:9)`

**Comment by kaushalkapasi** [comment]
Hey @emi-net21, thanks for creating this issue!

Couple of additional questions I have for you / your team:
1. Do you use realtime updates on the DevCycle Android SDK?
2. Does your app use coroutines / threads?

We'll start investigating on our end to see if we can reproduce this issue. Looking forward to hearing from you!

**Comment by emi-net21** [comment]
1-2: Yes, coroutines = "1.6.4"

Example we use:

`override suspend fun checkVariable(): Flow<Boolean> {
        return withContext(ioDispatcher) {
            val variable =
                dvcClient.variable(KEY, false)
            callbackFlow {
                trySend(
                    variable
                )
                variable {
                    trySend(it.value)
                }
                awaitClose()
            }
        }
    }`

Just to mentioned, we could not reproduce the crash, but saw a couple of them on Firebase Crashalitycs

**Comment by kaushalkapasi** [comment]
Awesome, thanks for the info! We're looking at adding some checks to make sure that an Executor is available before we establish our Realtime updates connection. Aiming to have that published sometime next week that should mitigate this issue.

**Comment by vinodkumarsagitla** [comment]
Hello @kaushalkapasi I also saw a lot of crashes on Firebase related to DevCycle code with above mention Exception.
Any update?

**Comment by kaushalkapasi** [comment]
Hey @vinodkumarsagitla, we have a PR ready! Just doing some internal testing before we publish a release! Are you able to share any more information about the crashes that you are seeing?

**Comment by vinodkumarsagitla** [comment]
@kaushalkapasi We are unable to reproduce this crash but saw lots of crashes on Firebase Crashalitycs. 
We are using:
devCycle = 1.4.2
coroutines = 1.6.4

**Comment by kaushalkapasi** [comment]
@emi-net21 & @vinodkumarsagitla we've released a new version of the Android SDK (1.4.4) that has a fix for this issue.

If you could test it out and let us know if it eliminates / reduces the number of crashes you are seeing then we can go ahead and resolve this issue!

Sorry for the delay on getting this out, appreciate your patience!

**Comment by VicV** [comment]
Hey @vinodkumarsagitla, just wanted to check in to ensure we can close this issue

**Comment by vinodkumarsagitla** [comment]
Hello @VicV, I am still waiting because my client have not release build yet after version update of DevCycle. I will inform you as soon as when my app is live.

**Comment by vinodkumarsagitla** [comment]
Hello @VicV  After new release we are unable to reproduce this crash but saw lots of crashes on Firebase Crashalitycs.
See below screen shot:
[https://www.dropbox.com/s/lsh3crqyl2bxtyh/1.png?dl=0](url)
[https://www.dropbox.com/s/vjkv8p5fpw47o6v/2.png?dl=0](url)

**Comment by leslie-lau** [comment]
HI @vinodkumarsagitla apologies, your follow-up went under our radar. Last you ran this, were you still seeing crashes on Firebase Crashlytics?

**Comment by jsalaber** [comment]
Closing this issue due to being unreproducible, please feel free to reopen with any further information if it's still happening
